### ISSUE TITLE
Race condition between token request and api calls when enabling oauth

### ISSUE THREAD

**Issue by NilsEngelbach** [flowcate/deephub-advanced-setup#4] opened 2024-05-27 07:38 UTC
I have enabled oauth as described in the documentation / code example here on github.

**Problem:**

I am stuck on the "Login" page, reloading the page or hitting the "Login" Button only works sporadicaly.

**Identified Cause:**

It seems to me that there is a race condition between getting the inital token and making the first api requests.

**Token Request is completed before first API Call:**

![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/6b3b849b-91ee-4fbf-86cc-f4f0a6f41d5a)

![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/2867e039-29ce-430b-b43a-43644239bdea)

**Token Request is completed after first API Call (stuck on login page):**

![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/73190697-b711-446d-867c-56a2cb743089)

![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/7fe8ef5f-269d-48f1-ad43-308a4e35f820)

Since it is an timing issue it is hard to reproduce but setting the network speed to "Fast 3G" in Chrome DEV Tools made it reproducible for me.

Version: 2.5.0

**Comment by wraromer** [comment] 2024-05-28 08:03
Hello Nils,

thanks for the report and especially the lengthy analysis. We will dig into this!

Wolfgang

**Comment by wraromer** [comment] 2024-05-28 11:10
@NilsEngelbach: In case it does not work, do you reach the keycloak authentication page at least - see attached screenshot - or what does exactly happen? 
![image](https://github.com/flowcate/deephub-advanced-setup/assets/23312565/cce409af-bf82-4c3d-9c74-e3a268729b39)

**Comment by NilsEngelbach** [comment] 2024-05-29 06:23
Initially I get redirected to the IDP for authentication, after that I am "stuck" on the "Login Screen".
Clicking "Login" reloads the page and with a little luck (timing as described above) the application opens...

I also recorded an example:
![login-2-blurred](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/fcfae756-349d-494b-9331-70bac485a9ca)

As you can see, as soon as i open the dev tools it works...

**Comment by wraromer** [comment] 2024-05-29 06:28
Concerning the screencast gif: Is it a coincidence that it always works in case the developer console is open?

**Comment by NilsEngelbach** [comment] 2024-05-29 06:49
I think due to the logging etc. that is going on when opening the dev tools, the timing is just different enough to make it work.
As mentioned if i change it to a slower network (e.g. Fast 3G) it always fails, even with Dev Tools open...

**Comment by wraromer** [comment] 2024-06-13 06:48
We are working on a fix which will be released as a 2.5.1 version of DeepHub 2024 R1.

**Comment by wraromer** [comment] 2024-06-28 08:05
The 2.5.1 bug fix release is now officially available. It fixes this race condition.

**Comment by NilsEngelbach** [comment] 2024-07-01 08:24
Thank you for the quick fix! I just tested with the 2.5.1 version and it works.

Only two small problems i noticed.

1. It used to be possible to enter the license key in the UI (when it was not provided as envrionment variable). It seems that this is no longer possible when enabling the authorization. I can see the screen to enter the license flashing up shortly, but then i am stuck on the login page. 

The /lease request has an error because it is missing the authoriation header:
![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/4476a384-b556-4ea2-b491-3b7aa8ef6f9e)
![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/d12d2cb0-6057-4b94-8432-2a0d3dd067eb)

And all the API request fail because the license is invalid:
![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/bfca8d94-bcbb-49c5-a746-fc733f7e6cac)
![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/8db89661-bd4f-409e-afa9-8d0facc8f452)

I also tried to add the `/lease` endpoint to the guest user in the `permissions.yaml` but this did not work either:

```yaml
guest:
  description: A read only guest access
  '/health':
    - READ_ANY
  '/version':
    - READ_ANY
  '/lease':
    - READ_ANY
```

Only solution for me was to provide the license key as environment variable.

2. The second "problem" i noticed is that it seems that the deephub is extracting the roles of the user from the `realm_access.roles` claim of the token. The claim name might be different for other identity provider than keycloak and ideally it would be configurable as environment variable as well (to support other claim names).

![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/e3db52ea-40ad-449d-baea-a42014590cb2)

**Comment by wraromer** [comment] 2024-07-01 08:34
Hello Nils,

concerning "It used to be possible to enter the license key in the UI": I would oppose this because you can login in the login screen and will then be redirected to the error page, claiming that no license was found or is invalid. There you can enter the license key.

I would therefore close this issue here as solved.

Concerning "deephub is extracting the roles of the user from the realm_access.roles claim of the token": we will dig into this.

Wolfgang

**Comment by NilsEngelbach** [comment] 2024-07-01 08:35
No I am not redirected to the page to enter the license key thats the point.

**Comment by wraromer** [comment] 2024-07-01 08:36
It works for us here. Could you please clear your browser's cache etc. to ensure that there is no "interference" with some older cookies etc., please.

**Comment by NilsEngelbach** [comment] 2024-07-01 08:45
![login-3-blurred](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/05125a1d-df98-48cd-acf8-c8437fefa4eb)

**Comment by wraromer** [comment] 2024-07-01 08:49
I can confirm this happening with the Firefox browser on my Windows machine. It works fine when using the Edge browser. We'll investigate.

**Comment by code-ha** [comment] 2024-09-20 17:46
Hello @NilsEngelbach , this has been fixed with the latest release of the DeepHub, version 2.5.3. Please let us know if everything looks good on your end.

**Closed as completed** 2024-09-27 16:12 UTC
